<template>
  <div class="p-5">
    <section>
      <h3>
      Technologies
      </h3>
      <h2>
        <ul>
          <li>aws</li>
          <li>kubernetes</li>
          <li>docker</li>
          <li>terraform</li>
          <li>snowflake</li>
          <li>databricks</li>
          <li>elasticsearch</li>
          <li>rds/aurora</li>
          <li>airflow</li>
          <li>prefect</li>
          <li>looker</li>
          <li>tableau</li>
        </ul>
      </h2>
    </section>
  </div>
</template>
